# Generated by Django 2.1.7 on 2019-04-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imgupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('customize', models.CharField(choices=[('GS', 'Grayscale'), ('BW', 'Black and White'), ('SP', 'Sepia'), ('DF', 'Deepfried')], default='GS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='loaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something', models.TextField()),
            ],
        ),
    ]
